# abc Trip Planner (MVP)

Members
* Daniel Jiang (1009509)
* John Mo (1009513)
* Timothy Zheng (1009502)

## Notes

To run this program, you will need to create and populate a `.env` file with your OpenAI API key

`.env`

```bash
OPENAI_API_KEY = "your_key_here"
```

### TODO
* Set up OpenAI key
* Implement LLM
* RAG system
* (eval) compare to "ground truth"

### Innovative "ideas"
* Take note of the places LLM suggests, then make LLM system search online for the prices of places. Then output estimated cost of trip.
* Approach the topic as a "narrative journey": Add the history of places, culture, etc and make attractions "references" to the narrative, instead of the primary focus. Make the narrative the primary focus.
* Attach a packing list
* Implement weather forecast into trip plan

In [3]:
%pip uninstall pandas -y
%pip uninstall numpy -y
%pip uninstall pytz -y
%pip uninstall python-dateutil -y

Found existing installation: pandas 2.0.3
Uninstalling pandas-2.0.3:
  Successfully uninstalled pandas-2.0.3
Note: you may need to restart the kernel to use updated packages.
Found existing installation: numpy 1.22.4
Uninstalling numpy-1.22.4:
  Successfully uninstalled numpy-1.22.4
Note: you may need to restart the kernel to use updated packages.


You can safely remove it manually.


Found existing installation: pytz 2024.2
Uninstalling pytz-2024.2:
  Successfully uninstalled pytz-2024.2
Note: you may need to restart the kernel to use updated packages.
Found existing installation: python-dateutil 2.9.0.post0
Uninstalling python-dateutil-2.9.0.post0:
  Successfully uninstalled python-dateutil-2.9.0.post0
Note: you may need to restart the kernel to use updated packages.


In [4]:
%pip install --upgrade pip --quiet
%pip install openai --quiet
%pip install python-dotenv --quiet
%pip install praw --quiet
%pip install pydantic --quiet
%pip install langchain-community --quiet
%pip install bs4 --quiet
%pip install pandas --quiet

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

In [5]:
from openai import OpenAI
from dotenv import load_dotenv
from IPython.display import display, Markdown, clear_output
import time

load_dotenv() # Requires .env file

True

In [6]:
client = OpenAI()

system_prompt = """You are a knowledgeable travel assistant. Provide a comprehensive and well-structured guide for the specified destination. Your response should be detailed, accurate, and formatted using markdown. Follow these guidelines:

1. Begin with a brief introduction about the destination.
2. Use level 2 headers (##) to separate main sections.
3. Use bolding (**) for subsections or important points within sections.
4. Include exclusively the following sections in exactly this order.
   - Best Time to Visit
   - Top Attractions
   - Local Culture and Etiquette
   - Getting Around
   - Food and Dining
   - Accommodation
   - Safety and Health
   - Budget Tips
   - Unique Experiences
   - Essential Phrases (if applicable)

5. Provide practical, up-to-date information and insider tips, highlighting any date-specific events if possible.
6. Use bullet points sparingly, preferring well-structured paragraphs.
7. Include any recent developments or changes affecting travel to the destination.
8. Conclude with a brief summary or final travel tip.

Aim for a comprehensive guide that's easy to read and informative for travelers."""

In [7]:
destination = "Chiang Mai"
stream = client.chat.completions.create(
    model="gpt-3.5-turbo-0125",
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Provide key travel tips for {destination}"}
    ],
    stream=True
)

full_response = ""
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        content = chunk.choices[0].delta.content
        full_response += content
        
        # Clear the current output and display the updated markdown
        clear_output(wait=True)
        display(Markdown(full_response))
        
        # Add a small delay to make the streaming visible
        time.sleep(0.01)

## Introduction
Chiang Mai, in northern Thailand, is a culturally rich city known for its ancient temples, vibrant markets, and lush mountain landscapes. With a relaxed atmosphere and warm hospitality, it's a favorite destination for travelers seeking a blend of history, nature, and spirituality.

## Best Time to Visit
**-** The best time to visit Chiang Mai is from **November to February** when the weather is cooler and dry, making it ideal for exploring the city and surrounding areas.
**-** Avoid visiting during the **burning season** (typically in March and April) when air quality can be poor due to agricultural burning.

## Top Attractions
**-** **Doi Suthep** - Visit this mountaintop temple for panoramic views of the city.
**-** **Old City** - Explore the ancient temples, including Wat Phra Singh and Wat Chedi Luang.
**-** **Sunday Night Market** - Experience the vibrant night market on Ratchadamnoen Road.
**-** **Chiang Mai Night Safari** - Enjoy a unique wildlife experience after dark.
**-** **Elephant Nature Park** - Interact ethically with rescued elephants in a natural setting.

## Local Culture and Etiquette
**-** **Respect for the King and the Royal Family** is essential in Thailand, so be mindful of any discussions or actions related to them.
**-** **Dress modestly** when visiting temples; both men and women should cover their shoulders and knees.
**-** **Remove your shoes** before entering someone's home or a temple.
**-** **Wai** - The traditional Thai greeting involves pressing your palms together in a prayer-like gesture.
**-** **Avoid public displays of affection** as they are considered inappropriate in Thai culture.

## Getting Around
**-** Get around the city easily by **tuk-tuk, songthaew** (shared red trucks), or **renting a scooter** for more flexibility.
**-** **Grab** is a convenient option for private transportation.
**-** Renting a bicycle is a popular way to explore the city center and its surroundings.

## Food and Dining
**-** **Try local dishes** such as Khao Soi (noodle curry soup) and Sai Oua (northern Thai sausage).
**-** Visit **Warorot Market** for a variety of street food and fresh produce.
**-** Consider taking a **cooking class** to learn how to make traditional Thai dishes.
**-** Don't miss out on **Mango Sticky Rice**, a popular and delicious dessert.

## Accommodation
**-** Chiang Mai offers a range of accommodations from **budget guesthouses** to **luxury resorts**.
**-** **Old City** and **Nimmanhaemin Road** are popular areas to stay due to their proximity to attractions and amenities.
**-** Consider staying in a **traditional Thai teak house** for a unique experience.

## Safety and Health
**-** **Drink bottled water** to avoid stomach issues.
**-** Be cautious when **renting scooters** and ensure you have the necessary license and insurance.
**-** Beware of **mosquitoes**; use repellent or wear long sleeves in the evenings.

## Budget Tips
**-** Enjoy **affordable street food** from local vendors for a taste of authentic Thai cuisine.
**-** **Haggle politely** at markets to get the best prices on souvenirs and clothing.
**-** Opt for **local transportation** options like songthaews instead of private taxis for savings.

## Unique Experiences
**-** Join a **monk chat** at a local temple to learn about Buddhism and Thai culture.
**-** Participate in a **traditional Lanna cooking class** to discover the unique flavors of northern Thai cuisine.
**-** Witness the **Yee Peng Lantern Festival** in November for a magical experience of releasing lanterns into the sky.

## Essential Phrases
**-** **Sawadee ka/kap** - Hello (female/male)
**-** **Kob khun ka/kap** - Thank you (female/male)
**-** **Mai pen rai** - No problem/You're welcome

In conclusion, Chiang Mai offers a blend of history, culture, and nature, making it a must-visit destination in Thailand. Respect local customs, try traditional dishes, and immerse yourself in unique experiences to make the most of your trip to this enchanting city.

***

## RAG Implementation

## TODO: Need to create system that dynamically finds reddit threads (maybe tripadvisor if time permits) given a location (refer to the diagram in slides to implement)
* Searches google API for places based on "things to do in <location> site:reddit.com" etc.

In [8]:
# code here
%pip install googlesearch-python

ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

In [9]:
from googlesearch import search

def fetchRedditLinks(dest):
    query = f"{dest} site:reddit.com" # or site:reddit.com/r/travel
    links = []

    for link in search(query, num_results = 25):
        links.append(link)

    return links

In [10]:
links = fetchRedditLinks(destination)

if links:
    print(f"Reddit Threads about {destination}")
    for link in links:
        print(f"- [{link}]({link})")
else:
    print(f"No Reddit threads found for {destination}")

Reddit Threads about Chiang Mai
- [https://www.reddit.com/r/chiangmai/](https://www.reddit.com/r/chiangmai/)
- [https://www.reddit.com/r/ThailandTourism/comments/1btp263/is_chiang_mai_worth_it/](https://www.reddit.com/r/ThailandTourism/comments/1btp263/is_chiang_mai_worth_it/)
- [https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/](https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/)
- [https://www.reddit.com/r/chiangmai/comments/1bmosut/chiang_mai_trip_report_places_to_eat_activities/](https://www.reddit.com/r/chiangmai/comments/1bmosut/chiang_mai_trip_report_places_to_eat_activities/)
- [https://www.reddit.com/r/chiangmai/comments/17m22ss/why_people_like_chiang_mai_i_dont_get_it/](https://www.reddit.com/r/chiangmai/comments/17m22ss/why_people_like_chiang_mai_i_dont_get_it/)
- [https://www.reddit.com/r/chiangmai/comments/1e9k6sx/whats_better_chiang_mai_or_hua_hin/](https://www.reddit.com/r/ch

### Testing
* Below is a test list of sources for Chiang Mai (still need to implement the system for fetching docs from Google)

In [11]:
sources = [
    'https://www.reddit.com/r/chiangmai/comments/1cb3fx4/yi_pengloi_krathong_2024/',
    'https://www.reddit.com/r/ThailandTourism/comments/1cpccho/yi_peng_festival_on_a_budget/',
    'https://www.reddit.com/r/ThailandTourism/comments/13b0gld/help_me_with_chiang_mai_itinerary/',
    'https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/',
    'https://www.reddit.com/r/chiangmai/comments/1er2mj4/things_to_do_in_chiang_mai/',
    'https://www.reddit.com/r/chiangmai/comments/1bmosut/chiang_mai_trip_report_places_to_eat_activities/',
    'https://www.reddit.com/r/chiangmai/comments/185wni7/what_to_do_in_chiang_mai/',
    
    # buggy tripadvisor
    'https://www.tripadvisor.com/ShowUserReviews-g293917-d8820428-r621075297-Yi_Peng_and_Loy_Krathong_Lantern_Festival-Chiang_Mai.html'
]

In [12]:
# New - use links from reddit
sources = links

In [13]:
import praw
import requests
from bs4 import BeautifulSoup, SoupStrainer
from urllib.parse import urlparse
import pandas as pd
import time
from typing import List, Dict
import os


### Reddit API Key
Create a Reddit API key by following the instructions [here](https://www.reddit.com/prefs/apps) (create a script)

add the following to your `.env` file
```bash
REDDIT_CLIENT_ID = "<your-reddit-client-id>"
REDDIT_CLIENT_SECRET = "<your-reddit-client-secret>" 
REDDIT_USER_AGENT = "python:<app-name>:v1.0 (by /u/<your-reddit-username>)"
```

In [14]:
# Scrape reddit using praw

# using praw to better seperate reddit data
reddit = praw.Reddit(
    client_id=os.environ.get("REDDIT_CLIENT_ID"),
    client_secret=os.environ.get("REDDIT_CLIENT_SECRET"),
    user_agent=os.environ.get("REDDIT_USER_AGENT"),
)

def scrape_reddit_post(url: str) -> Dict:
    """Scrape content from a Reddit post."""
    try:
        # Extract post ID from URL
        submission_id = url.split('comments/')[1].split('/')[0]
        submission = reddit.submission(id=submission_id)
        
        # Get post content
        post_data = {
            'title': submission.title,
            'text': submission.selftext,
            'comments': [],
            'url': url,
            'source': 'reddit'
        }
        
        # Get comments (limit to top-level comments)
        submission.comments.replace_more(limit=0)
        for comment in submission.comments:
            if not comment.stickied:  # Skip stickied comments
                post_data['comments'].append(comment.body)
        
        return post_data
    
    except Exception as e:
        print(f"Error scraping Reddit post {url}: {str(e)}")
        return None


In [15]:
from langchain_community.document_loaders import WebBaseLoader

# TODO scraping tripadvisor is too buggy keeps getting rate limited
def scrape_tripadvisor(url: str):
    loader = WebBaseLoader(
    web_paths=(url,),
    bs_kwargs=dict(
        parse_only=SoupStrainer(
            class_=("post-content", "post-title", "post-header")
            )
        ),
    )
    return loader.load()[0]

USER_AGENT environment variable not set, consider setting it to identify your requests.


In [16]:
# Combined function
def scrape_urls(urls: List[str]) -> pd.DataFrame:
    """Scrape content from a list of URLs."""
    scraped_data = []
    
    for url in urls:
        print(f"Scraping {url}")
        domain = urlparse(url).netloc
        
        # Add delay between requests
        time.sleep(1)
        
        if 'reddit.com' in domain:
            data = scrape_reddit_post(url)
        else:
            data = scrape_tripadvisor(url)
            
        if data:
            scraped_data.append(data)
    
    # Convert to DataFrame
    df = pd.DataFrame(scraped_data)
    return df

# non-reddit links keep getting rate limited
# display(scrape_urls(['https://www.tripadvisor.com/ShowUserReviews-g293917-d8820428-r621075297-Yi_Peng_and_Loy_Krathong_Lantern_Festival-Chiang_Mai.html']))

In [17]:
# Scrape reddit only
reddit_results = scrape_urls([s for s in sources if 'reddit' in s])

# Display first few rows
display(reddit_results.head())

Scraping https://www.reddit.com/r/chiangmai/
Error scraping Reddit post https://www.reddit.com/r/chiangmai/: list index out of range
Scraping https://www.reddit.com/r/ThailandTourism/comments/1btp263/is_chiang_mai_worth_it/
Scraping https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/
Scraping https://www.reddit.com/r/chiangmai/comments/1bmosut/chiang_mai_trip_report_places_to_eat_activities/
Scraping https://www.reddit.com/r/chiangmai/comments/17m22ss/why_people_like_chiang_mai_i_dont_get_it/
Scraping https://www.reddit.com/r/chiangmai/comments/1e9k6sx/whats_better_chiang_mai_or_hua_hin/
Scraping https://www.reddit.com/r/ThailandTourism/comments/d8b7pl/what_are_some_must_things_to_do_at_chiang_mai/
Scraping https://www.reddit.com/r/ThailandTourism/comments/15qvc85/chang_mai_how_much_time_is_too_much/
Scraping https://www.reddit.com/r/ThailandTourism/comments/123syod/interesting_different_things_to_do_in_chiang_mai/
Scraping https://www.red

title  \
0                            is chiang mai worth it?   
1  4 days trip in Chiang Mai - Any suggestions fo...   
2  Chiang Mai Trip Report / Places to eat & Activ...   
3        Why people like Chiang Mai? I don't get it.   
4             What’s better:  Chiang Mai or Hua Hin?   

                                                text  \
0  hello! typical 20 something backpacker trash f...   
1  Hello all! I'm planning on a solo trip to Chia...   
2   \n\nHello World!\n\nThis   is my first thread...   
3  From all the cool places I've been so far in T...   
4  Anyone lived in both cities?  Advantages and d...   

                                            comments  \
0  [The food alone is worth it IMO. and the atmos...   
1  [Sticky waterfall: a wonder that will mess wit...   
2  [Thanks for taking the time to write this. It’...   
3  [The cost of living here is significantly lowe...   
4  [[deleted], For living year round or what?\n\n...   

                                                 url  source  
0  https://www.reddit.com/r/ThailandTourism/comme...  reddit  
1  https://www.reddit.com/r/chiangmai/comments/1e...  reddit  
2  https://www.reddit.com/r/chiangmai/comments/1b...  reddit  
3  https://www.reddit.com/r/chiangmai/comments/17...  reddit  
4  https://www.reddit.com/r/chiangmai/comments/1e...  reddit

### Encode Reddit data in single string for embedding

Target structure (Markdown):

* Markdown performance in GPT-4 is cheaper and more token-efficient
- https://arxiv.org/html/2411.10541v1
   - GPT-3.5-turbo prefers JSON, whereas GPT-4 favors Markdown
   - Encode in markdown since we are using GPT-4
- https://community.openai.com/t/markdown-is-15-more-token-efficient-than-json/841742

In [18]:
first_post = reddit_results.iloc[0]
first_post

title                                 is chiang mai worth it?
text        hello! typical 20 something backpacker trash f...
comments    [The food alone is worth it IMO. and the atmos...
url         https://www.reddit.com/r/ThailandTourism/comme...
source                                                 reddit
Name: 0, dtype: object

In [19]:
from dataclasses import dataclass
from typing import List
import textwrap

@dataclass
class RedditThread:
    title: str
    text: str
    comments: List[str]
    url: str
    source: str
    
    def __str__(self) -> str:
        # Format the main post
        output = [
            f"# {self.title}",
            "",
            f"## Original Post",
            "",
            textwrap.fill(self.text, width=80),
            "",
            "### Comments",
            ""
        ]
        
        # Format comments with indentation to show thread structure
        for comment in self.comments:
            # Calculate comment depth based on leading spaces
            depth = len(comment) - len(comment.lstrip())
            # Remove leading spaces and wrap text
            clean_comment = comment.lstrip()
            # Add markdown list marker with proper indentation
            indent = "  " * (depth // 2)  # Adjust indentation based on depth
            wrapped_comment = textwrap.fill(
                clean_comment,
                width=80,
                initial_indent=f"{indent}- ",
                subsequent_indent=f"{indent}  "
            )
            output.append(wrapped_comment)
        
        output += [
            "",
            "#### URL",
            self.url
        ]
        
        return "\n".join(output)
    
    def get_comments_as_str(self):
        output = ["### Comments"]
        # Format comments with indentation to show thread structure
        for comment in self.comments:
            # Calculate comment depth based on leading spaces
            depth = len(comment) - len(comment.lstrip())
            # Remove leading spaces and wrap text
            clean_comment = comment.lstrip()
            # Add markdown list marker with proper indentation
            indent = "  " * (depth // 2)  # Adjust indentation based on depth
            wrapped_comment = textwrap.fill(
                clean_comment,
                width=80,
                initial_indent=f"{indent}- ",
                subsequent_indent=f"{indent}  "
            )
            output.append(wrapped_comment)
        return "\n".join(output)

In [20]:
reddit_threads = [RedditThread(
    title=row['title'],
    text=row['text'],
    comments=row['comments'],
    url=row['url'],
    source=row['source']
) for index, row in reddit_results.iterrows()]

In [21]:
str(reddit_threads[0])

'# is chiang mai worth it?\n\n## Original Post\n\nhello! typical 20 something backpacker trash from the US here. i’ve been in\nthailand for a week, just bangkok and the south, and wanted to get reddit’s\nthoughts on this:  I have about 2 more weeks allotted for thailand, then a week\nfor laos, then i’m off to vietnam.   I was going to do chiang mai and pai for\nlike a week-ish before heading off to laos, but everything i’ve read about both\nplaces says they’re so saturated in tourists (not that i’m helping). I’m not\nconcerned about the smoke, I’m from northern california so we also have “free-\ntrial-of-Hell” season 😂😂.   For a first time backpacker to SE asia, are pai and\nchiang mai must-dos, or would it be more worth it to skip the tourist traps and\nget authentic experiences in northern laos instead?\n\n### Comments\n\n- The food alone is worth it IMO. and the atmosphere at night, cool little bars,\n  live music smaller groups more intimate. Easy to meet people and not get too\n  

In [22]:
display(Markdown(str(reddit_threads[0])))

# is chiang mai worth it?

## Original Post

hello! typical 20 something backpacker trash from the US here. i’ve been in
thailand for a week, just bangkok and the south, and wanted to get reddit’s
thoughts on this:  I have about 2 more weeks allotted for thailand, then a week
for laos, then i’m off to vietnam.   I was going to do chiang mai and pai for
like a week-ish before heading off to laos, but everything i’ve read about both
places says they’re so saturated in tourists (not that i’m helping). I’m not
concerned about the smoke, I’m from northern california so we also have “free-
trial-of-Hell” season 😂😂.   For a first time backpacker to SE asia, are pai and
chiang mai must-dos, or would it be more worth it to skip the tourist traps and
get authentic experiences in northern laos instead?

### Comments

- The food alone is worth it IMO. and the atmosphere at night, cool little bars,
  live music smaller groups more intimate. Easy to meet people and not get too
  wild vs say Bangkok.   The vibe is very chill... "slow life" we call it.  Some
  cool stuff to see too depending on what you are interested in.
- For me, CM and the north are absolutely a must and I find it hilarious that
  you've been to the south (assuming islands) and call the north a tourist trap.
  It's in the north (and Bangkok) that you meet the real Thailand, imo.
- Go eat some Khao Soi in Chiang Mai to earn the bragging rights when you go
  back home.
- I'm just curious, what is a "typical 20 something backpacker trash" ? 😆
- Chang mai and pai are a must imo
- We were just in Chiang Mai 10 days ago. We were also in Bangkok and Krabi.
  Bangkok is huge and chaotic, and mostly feels like an Asian metropolis. Krabi
  was either too provincial or too touristy depending on where we were. Chiang
  Mai is more of a mid-sized city, with trendy cafes, shops and bars, old
  neighborhoods and newer fancier ones. I think it felt a bit more like being in
  South East Asia in general, so it added that extra flavor to our trip.
- I loved chiang mai ! Just came from there yesterday and now in the south. If I
  were to do it again (which I would) I would: - skip Chiang Rai > way too
  touristy and horribly too hot to walk around and enjoy the temples tbh  - hang
  out at the sticky waterfalls, honestly so fun - Wat Pha La -> only temples
  I’ve cared about in Thailand and really serene  - Dantewada cafe -> beautiful
  waterfall “park” but looks like out of a fairytale could spend the whole day
  there
- You'll be missing out if you don't.  Very weird that you don't consider
  bangkok and the south saturated with tourists but you think the north is?
  Northern Thailand is amazing. And right now I would say it's quite quiet. Not
  so many tourists.  Go to Chiang Mai, eat some amazing food (I recommend Khao
  Soi Islam Noodles for Khao Soi). Don't forget to check out the North Gate food
  market. Explore the Old City, check out some cool lil bars. See some live
  music at North Gate Jazz Co-op. Id also recommend "The Simple man" bar, the
  owner is a great guy. Go go the Sticky Waterfall, temples, Doi Suthep etc.
  Then get yourself up to Pai. Go "Tipsy tubing", go on some day trips, visit
  the Chinese Village, waterfalls (Though some of them might be pretty dry
  now?). Loads of great bars here, main recommend would be Almost Famous,
  amazing mojitos. Also Jikko Beer. Catch a sunset at Pai Canyon (Not great if
  your scared of heights), catch another sunset at Two Huts on another evening.
  There's a few different viewpoints around that are well worth it.  Just a
  note, if you do go to Pai and you go tubing, go with "Tipsy tubing" booked at
  Pai Authentic Travel. There's another company (previously Jungle Tubing but
  changed it's name to Tipsy Jungle Tubing) with some very deceitful and bad
  faith business practices.
- I’ve been going to Thailand for the last 8 years. Basically live there at this
  point. I’d been everywhere. But I never went to Chiang Mai. Until late last
  year. I loved it. I would go. Rent a motorcycle and do the loop. Visit some
  places outside of Chiang Mai. Chiang Dao. Chiang Rai. Or just stay right in
  Chiang Mai.  Definitely have breakfast at Breakfast World Chiang Mai.
  Definitely go to doi Inthanon. Definitely go to doi suthep.   I would go.
- I love Chiang Mai. Its has a chilled out slow living vibe. I used to climb up
  Doi Suthep with my bicycle, have some noodle, coffee or fresh strawberry
  smoothie up in the mountain. Then come back down for a 30b chicken rice at the
  university. When it gets super hot, get some coconut ice cream and kaniau
  mamuang near the gate. 
- Absolutely! I was there last week and it's a great city to visit, a must I
  would say. Please, if you are going to the north, also visit Pai. If you like
  to scooter there, it's a really fun road from Chiang Mai to Pai and will only
  take about 3 hours or a bit longer if you take it easy.
- Absolutely worth it. Go further up into the mountains and stay at Mae Rim…so
  gorgeous and has the Queens elephant sanctuary and the restaurant at Proud Phu
  Fa Hip Resort. As authentic as it gets.
- Absolutely. One of my favorite places in Thailand. Do not skip it.
- if your in Thailand you DEFINITELY need to take the night train to Chiang mai.
  it's such an awesome chilled out town with lots of stuff to do. plus there's
  Chiang Rai about 6 hours away where they have magic mushroom shakes which
  taste fantastic if you so choose to indulge. :)
- If you like art in any shape or form, CM is a must
- Chiang Mai is cozy and cool, so different from Bangkok. Especially in the old
  city. Seems like other country in a way which is reasonable if we consider the
  fact that historically northern Thailand had their own kingdom. Even writing
  system was different. And i like that they wear traditional clothes much more
  often than in Bangkok or other big cities in Thailand. You can go to Sukhothai
  - another historical city - for 2 or 3 days and from there its like 4-5 hours
  of bus ride to CM Good luck my friend
- Absolutely worth it. Especially for Songkran Festival.
- Yes it’s worth it and so is Pai. Depends on what you mean by getting more
  authentic experiences though.
- The food is amazing! I stayed at a dream hotel while I was there and I
  absolutely can’t say enough good things!
- Just left Chiang Mai and so far it’s been the highlight of the trip.
  Definitely recommend. It is super hot but I’ve been hot since I got here 😂
- If I could only choose between Chiang Mai and BangKok, I much rather hang out
  in Chiang Mai.
- Cm is awesome, spent 3 weeks there. 3.5 months total all over Thailand. The
  Sunday night street market is a lot of fun and so much food to try. CM and Koh
  Samui were my top picks.
- Chaing Mai is one of my favourite city’s, I didnt make it to pai as ended up
  spending 7 days in cm
- My favourite city CM is cool and best from Nov to Jan
- Chiang Mai is 100% worth it, I’m here now then heading to Laos also on the
  7th! When I was in Pai I wasn’t the biggest fan but Chiang Mai is cool as fuck
- I liked Chiang Mai, never got to Pai. Songkran starts in a couple of weeks.
  Probably not good to be traveling that weekend.
- CM and area is quite nice to explore. Its a different facette of Thailand. I
  did not like Pai though.
- I loved Chiang Mai the most
- 2 major reasons: Khao Soi, and Namton’s House Bar.
- Food in Chiang Mai was some of my favorite. Since it’s smaller of the major
  known cities or tourist hubs it can feel over touristed but it’s still a place
  I’ll keep returning too.
- Yes absolutely. My only regret on my trip was spending more time in Bangkok
  than Chiang Mai.
- I loved Chiang Mai!!! The vibe there is so chill!!   If you are going to go -
  Stamps is supposed to be a really good hostel, my friends were staying there,
  I had already booked the Amora hotel round the corner. Both are great location
  just outside the city wall. Khao Soi is 👌👌 I would go back just to eat more of
  that. I also did a cooking class with Aromdii which I would highly recommend!!
  Also go for a Sunday night for the market it’s enormous, I got some really
  cool art for 500baht!  I didn’t go to Pai as I only had 3 days up north but I
  think you can do it as a day trip from Chiang mai if you don’t want to stay
  there.
- I was in Chiang Mai for two nights and really liked it. Wished I had more
  time. I did a one day Viator tour that included an elephant sanctuary, the top
  of Thailand’s tallest mountain, and a jungle hike. That was the best part of
  my Thailand visit. But I also loved the other wats on the surrounding
  mountains and walking around the old town. The artist night market on Sunday
  night was awesome. I didn’t get to see everything I wanted to see so I would
  say a week in Chiang Mai is totally worth it.
- This! (and many other comments that are very accurately *pro* north and CM).
  One week would be enough for me between CM and CR.  I might reallocate the
  other week to VN but you weren’t clear how long you’d be in VN.  Laos would be
  a relatively short part of my Thailand-Laos-Vietnam trip  Dude is also totally
  right about calling the north a tourist trap after having been in the south.
  The north tends to have more Chinese tourists than the south
- If you go to Chiang Mai, get the pork leg (Khao ka moo), or that coarse
  grilled sausage. Don't know what that's called. 
- Yes. Doi Suthep Temple and Wat Phra Sing are must-see!
- Totally worth it. But in the old town.
- Well if youre looking for super authentic.... Youre definitely going to get
  more of that in Laos than in CM or Pai.... Both CM and Pai are tourist
  cities.... Which comes with many pros and cons... such as lots of things to
  do.  Theres lots of places in north Thailand that arent as touristy if that is
  your thing... Authentic.... Check out Nan, its like the hidden gem of the
  north (maybe I shouldn't advertise it here)... River town. Just see the Google
  images and thank me later.  You can also check out Chiang Rai, Mae Sai and
  Chiang Saen.
- i'm here in phuket at the moment, am about to go onto the islands. we have 2
  months total. i very briefly visited chiang mai on my last trip - 5 days, and
  i can say that the food is in my opinion my favourite + the architecture and
  landscapes are beautiful. only reason we didn't add it to the itinerary this
  time around is the air quality right now, bangkok was enough north for us. we
  will do chiang mai and pai at another time of the year.
- Everywhere new is worth it, each experience is different for every person, I
  never understand these cherry picking posts, listening to other people takes
  away a lot of the experience, the bad times are something you need to have to
  get the most from backpacking, you’ll  learn a few things about yourself.
  Everybody says places are tourist saturated but they only go to the places
  specifically for tourists, even in Bangkok you can live a 5 minute bike ride
  from asok BTS and never see a tourist if you choose, just look up places you
  think you’d like and go, and go see for yourself, you can always move on if
  it’s not your thing 👍
- The vibes in Chiang Mai are immaculate, everything felt so chill, the locals
  are absolute sweethearts, I didn’t encounter anyone trying to scam me or other
  bullshit.  I think everyone should visit Chiang Mai when visiting Thailand .
  Go to Elephant nature park! I did the highlands tour, so worth it.
- *authentic experiences*   No smartphones, no cars? We like to take care of our
  culture doesn't mean it's not authentic. For example, people from neighboring
  countries still come to Thailand to study Thai traditional dance, Pali
  language to this day. I'm in awe you think Thai culture in Thailand is not
  authentic when it's us have been sharing our knowledge to others.
  [https://thebuddh.com/?p=75882](https://thebuddh.com/?p=75882)  And If you're
  a mountain person, Northern VN is the most scenic. Southern Laos has Anthrax
  outbreak rn.
- Absolutely. This year will be our 3rd year going there to live for a month.
  What my wife and I liked the most was slow pace of things, good food, the
  general chill vibe of the city, and COFFEE. OMG so many coffee shops
  everywhere!  We're seriously considering if we should semi-permantly move
  there or at least get an apartment in the near future. We both work remotely
  so work isn't that big of an issue for us.
- Just go to Chiang Rai, better food and better sights. Chiang Mai is ok but
  probably my least liked "tourist" destination in Thailand. Just my opinion.
  Doesn't mean it's bad, I've enjoyed every time I was there but to me, there a
  so many better places. Thai wife so we go for at least a month every year.
- If you love the mountain it’s a must. A lot of nature and hikes around CM.
- It’s worth it if you go eat Khao Soi at Mr Kai’s
- Simple answer, yes. Go further north as well.
- Chiang Mai is great and way better than Bangkok or Phuket IMO
- Looking at Chiang Mai in Oct 2024.  Are there any recommended areas for
  accommodation or food / restaurants ??  thanks
- I enjoyed Chiang Mai. is def different pace it seems from the south. - I look
  forward to being back, but for alternate reasons from the temples/hikes/eats.
  -- If you have a spare few days, stop in.
- We spent 3 weeks in northern Thailand in December and absolutely loved it. 2
  of those weeks was a road trip which included the Mae Hong Son loop and then
  we headed further north before ending in Chiang Rai. I did a video series of
  the road trip here.
  https://youtube.com/playlist?list=PLqsPnQnZAxlyJPHAKElfHdF-
  sWR7iBPod&si=0CTa9Z2nfq5NHTWh
- Watch your ass in Laos. I'm not fucking with you.
- I would possibly skip Pai.  It's a bit of a cliche now.
- CM is at 30% occupancy at the moment.
- If you really travel in the north you will see real Thailand if you go to CM
  and just hanging around old city and then Pai you will see nothing.
- Pai was my favourite place in northern Thailand. Was supposed to stay 3 days
  and stayed 5. Really chilled out backpacker place with less holiday tourists.
- Laos is gonna be your favourite and you'll wish you spent more than a week
  there.   Chiang Mai is great though
- Yes worth it. I don’t think they’re touristy compared to the south
- Yes! Elephants,quite place, and the Cabaret Show😆
- Sure it is..
- I love the north! Chiangmai is a must! Pai is a gorgeous area. The town itself
  was a little too backpacker boutique style for my preference. I heard
  Chiangrai is great and has that really cool looking white temple I’ve been
  wanting to see.   For northern foods, I love khao soi and nam ngiao as well as
  the sai uwa sausages the region is known for. If you are adventurous, they
  have a signature larb salad made with fresh blood and bile. I’m curious to try
  it but it seems a little outside my wheelhouse
- Hey check out my trip report on Chiang Mai. It’s defo worth it xx
  https://www.reddit.com/r/ThailandTourism/s/twWOYFHT3a
- Sign up for one day free meditation experience at a local university if you
  have time. It is a great way to learn about monks daily routines and making
  connections.
- Chiang mai is pretty cool. It’s probably the hippiest-type of place you’ll
  find in SEA. There’s a lot of chill people there from all over the world.
  Architecturally it’s a pretty intriguing city with ancient gates and moats in
  a square feudal-vibes’ pattern. It’s a great city to walk around and snack and
  chill.
- I have been to Chiang Mai 3 weeks ago. I visited Krabi for first time (it was
  great, relaxing and beautiful). Then I flew to Chiang Mai. To be honest, I
  hesitated a lot before going there because of some sub-reddit comments about
  it that says "if you like beaches don't go to Chiang Mai". I do agree with
  that. I stayed for 5 days which I felt 3 days were enough. I like Thailand
  stunning beaches which Chiang Mai lacks of.
- Call me crazy but I’ve never liked Chang Mai. It’s like the Portland Oregon of
  Thailand.
- I've hardly seen any western tourists in Chiang Mai this week, the air
  pollution and heat must have scared them off. Lots of Thai's and Chinese.
  Hardly crowded, probably be of the better times to visit. It's as really hot,
  but dry hot, so I find it quite pleasant at 38°c
- Definitely go! As you are heading to Laos anyways after, see if you are up for
  a slow boat into Laos (Luang Prabang) from Chaing rai / Chiang mai. It takes
  about 2-3 days but if definitely a backpack adventure checklist
- I have a home in Chiang Mai that I visit once a year. Do Chiang Mai. You won’t
  need a week though
- Yes great city
- Yes yes yes
- Pai is super touristy, Chiang Mai doesn’t feel that way. It’s big and the
  tourists stick to specific areas (night bazaar, Tha Phae, and parts of the old
  city). The rest you won’t bump into many tourists
- This is what we got up to in Chiang Mai.. check it out see if anything takes
  your fancy x  https://www.reddit.com/r/ThailandTourism/s/w5v1GwbSvJ
- I'd say skip and go to Lao straight 
- It’s a nice town but quite small so would not stay there too long
- Theres not much to do im there now

#### URL
https://www.reddit.com/r/ThailandTourism/comments/1btp263/is_chiang_mai_worth_it/

### Add reddit data into vector store

In [23]:
%pip install --quiet sentence-transformers
%pip install --quiet langchain
%pip install --quiet langchain_openai

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

In [24]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="gpt-4o"
)

In [25]:
reddit_thread_strings = [str(t) for t in reddit_threads] # not being used anymore

In [29]:
pip install chromadb

  You can safely remove it manually.
ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run



  Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl.metadata (5.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
   --------------------------------------- 628.3/628.3 kB 11.8 MB/s eta 0:00:00
   ---------------------------------------- 4.4/4.4 MB 20.4 MB/s eta 0:00:00
   ---------------------------------------- 1.9/1.9 MB 20.4 MB/s eta 0:00:00
Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
   ---------------------------------------- 11.1/11.1 MB 913.7 kB/s eta 0:00:00
   ---------------------------------------- 1.2/1.2 MB 15.2 MB/s eta 0:00:00
  Created wheel for pypika: filename=PyPika-0.48.9-py2.py3-none-any.whl size=53835 sha256=2728fbd3f9faae8838796cf2121b7dd10590bb9e89cb089fb32d779eb8

    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '4.0.0-unsupported'


In [30]:
import torch

def get_device():
    if torch.backends.mps.is_available():
        if torch.backends.mps.is_built():
            return "mps"
    return "cpu"

get_device()

'cpu'

In [31]:
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.schema import Document
import numpy as np
from typing import List, Optional
import re


def create_reddit_vectorstore(
    reddit_threads: List[RedditThread], 
    persist_directory: str = "./chroma_db",
) -> Chroma:
# Initialize embeddings model
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L12-v2", # allows embedding the entire reddit thread, which is probably more useful
        model_kwargs={'device': get_device()}
    )
    
    # Convert threads to Documents with metadata
    documents = []
    for i, thread in enumerate(reddit_threads):
        metadata = {
            "thread_id": i,
            "title": thread.title,
            "content": thread.text,
            "comments": thread.get_comments_as_str(),
            "url": thread.url,
            "type": "reddit_thread",
        }
        
        doc = Document(
            page_content=str(thread),
            metadata=metadata
        )
        documents.append(doc)
    
    vectorstore = Chroma.from_documents(
        documents=documents,
        embedding=embeddings,
        persist_directory=persist_directory
    )
    
    vectorstore.persist()
    return vectorstore

# Create vectorstore
vectorstore = create_reddit_vectorstore(reddit_threads)

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 3,
        "filter": None,
    }
)

<ipython-input-31-400180f84254>:43: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  vectorstore.persist()


In [33]:
from langchain_core.prompts import ChatPromptTemplate

rag_system_prompt = (
    "You're a helpful AI assistant. Given a user question "
    "and some Reddit reddit threads formatted in markdown format composing of user questions and comments, answer the user "
    "question using the replies in the comments based on the topic of the thread. If none of the threads answer the question, "
    "just say you don't know."
    "\n\nHere are the Reddit Threads in full: "
    "{context}"
)

rag_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", rag_system_prompt),
        ("human", "{input}"),
    ]
)

In [34]:
def format_reddit_threads(threads):
    enumerated_reddit_threads = [
        f"Source ID: {i}\nReddit Thread: {thread}"
        for i, thread in enumerate(threads)
    ]

    return "\n\n" + "\n\n".join(enumerated_reddit_threads)


In [35]:
from pydantic import BaseModel, Field
from langchain_core.runnables import RunnablePassthrough


class Citation(BaseModel):
    source_id: int = Field(
        ...,
        description="The integer ID of a SPECIFIC source which justifies the answer.",
    )
    quote: str = Field(
        ...,
        description="The VERBATIM quote from the specified source that justifies the answer.",
    )


class QuotedAnswer(BaseModel):
    """Answer the user question based only on the given sources, and cite the sources used."""

    answer: str = Field(
        ...,
        description="The answer to the user question, which is based only on the given sources.",
    )
    citations: List[Citation] = Field(
        ..., description="Citations from the given sources that justify the answer."
    )

rag_chain_from_docs = (
    RunnablePassthrough.assign(context=(lambda x: format_reddit_threads(x["context"])))
    | rag_prompt
    | llm.with_structured_output(QuotedAnswer)
)


retrieve_docs = (lambda x: x["input"]) | retriever

chain = RunnablePassthrough.assign(context=retrieve_docs).assign(
    answer=rag_chain_from_docs
)

In [36]:
result = chain.invoke({"input": f"What is a must-eat food in {destination}?"})

In [37]:
result["answer"]

QuotedAnswer(answer='A must-eat food in Chiang Mai is Khao Soi. This dish is highly recommended by many travelers for its delicious taste. Additionally, you might want to explore other Lanna (northern Thai) dishes such as Gaeng Hung Lay and Nam Prik Ong, which are also quite popular.', citations=[Citation(source_id=0, quote='2. Khao soi is the best! Street food is a really great way to try a little bit of everything.'), Citation(source_id=1, quote="Besides Khao Soi & Pad Thai, are there any local delicacy that is a must try ? Pad Thai is not a local delicacy, but that aside, do make sure you explore Lanna (northern) Thai food of which khao soi is only one dish and there's some great dishes to try, including nam prik ong, guang hung lay, sai ua and more.")])

In [38]:
result["answer"].answer

'A must-eat food in Chiang Mai is Khao Soi. This dish is highly recommended by many travelers for its delicious taste. Additionally, you might want to explore other Lanna (northern Thai) dishes such as Gaeng Hung Lay and Nam Prik Ong, which are also quite popular.'

In [39]:
import json
def format_citations_to_json(citations: List[Citation], retrieved_docs) -> str:
    # Convert citations to list of dictionaries
    citations_dict = [citation.model_dump() for citation in citations]
    
    # Add URLs using source_id
    for citation in citations_dict:
        citation["url"] = retrieved_docs[citation["source_id"]].metadata["url"]
    
    
    # Convert to JSON with proper formatting
    json_output = json.dumps(citations_dict, indent=2)
    return json_output

In [40]:
print(format_citations_to_json(result["answer"].citations, result['context']))

[
  {
    "source_id": 0,
    "quote": "2. Khao soi is the best! Street food is a really great way to try a little bit of everything.",
    "url": "https://www.reddit.com/r/ThailandTourism/comments/d8b7pl/what_are_some_must_things_to_do_at_chiang_mai/"
  },
  {
    "source_id": 1,
    "quote": "Besides Khao Soi & Pad Thai, are there any local delicacy that is a must try ? Pad Thai is not a local delicacy, but that aside, do make sure you explore Lanna (northern) Thai food of which khao soi is only one dish and there's some great dishes to try, including nam prik ong, guang hung lay, sai ua and more.",
    "url": "https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/"
  }
]


In [41]:
first_result = result['context'][0]
print(first_result.page_content)

print("Metadata")

import json

print(json.dumps(
    first_result.metadata,
    sort_keys=False,
    indent=4,
    separators=(',', ': ')
))

# What are some must things to do at Chiang Mai

## Original Post

My partner and I are planning to visit Chaing Mai and would love suggestions to
some questions based on your experiences. We are planning to be there early
December this year and both of us love nature, parks and food (not into
partying)  1) What are some of the must do things there? (Both of us would love
to see elephants)   2) What are some of the must have food? (I have heard that
Khao soi is amazing)   3) What are some of the must go to locations that are not
that touristy?   4) How long would be an ideal stay?

### Comments

- 1. Definitely check out an elephant sanctuary (no riding!) and taking a
  cooking class (I really liked Asian Scenic.) I loved looking at the temples,
  especially Wat Phrathat Doi Suthep and Wat Chedi Luang. Night market is
  definitely a must do. 2. Khao soi is the best! Street food is a really great
  way to try a little bit of everything. 3. Driving out to Huay Tung Tao lake
  was one of 

In [42]:
# Here's all the context
result['context']

[Document(metadata={'comments': '### Comments\n- 1. Definitely check out an elephant sanctuary (no riding!) and taking a\n  cooking class (I really liked Asian Scenic.) I loved looking at the temples,\n  especially Wat Phrathat Doi Suthep and Wat Chedi Luang. Night market is\n  definitely a must do. 2. Khao soi is the best! Street food is a really great\n  way to try a little bit of everything. 3. Driving out to Huay Tung Tao lake\n  was one of my favorite parts of our trip. You can sit out on the lake and\n  relax and eat.  4. I would say a week! If you\'re into non-touristy stuff you\n  might also enjoy checking out Chiang Rai, particularly the White Temple and\n  the Black House.\n- Hello! Chiang Mai is such a wonderful, unassuming city. So you’re already\n  making a great decision to visit!  1) There are plenty of tours that offer to\n  take you to see elephants. Just make sure you choose one that doesn’t let you\n  ride them. I’ve done it with [Blue Elephant Thailand\n  Tours](htt

### Generate list of cited claims to add to the enriched RAG answer
* Small change in architecture: our program will output a list of cited claims, which is then passed into the LLM to generate the final answer.

In [43]:
rag_queries = [
    # Core travel information
    f"What are the most underrated or secret spots in {destination} that tourists usually miss?",
    f"What's the current situation with tourists in {destination} as of 2024?",
    f"What are common tourist scams to avoid in {destination} right now?",
    
    # Local insights
    f"Locals of {destination}, what tips would you give to tourists in 2024?",
    f"What are the best neighborhoods to stay in {destination} for different budgets?",
    f"What's the best way to get around {destination} nowadays?",
    
    # Food and culture
    f"What are must-try local foods in {destination} and where to find them?",
    f"What cultural faux pas should tourists avoid in {destination}?",
    f"Which local festivals or events are worth planning a trip around in {destination}?",
    
    # Practical advice
    f"How much does everything cost in {destination} in 2024?",
    f"What's the best time to visit {destination} and why?",
    f"What should I absolutely pack for {destination} that most tourists forget?",
    
    # Safety and logistics
    f"How safe is {destination} for solo travelers in 2024?",
    f"What areas should tourists avoid in {destination}?",
    f"What's the current transportation situation in {destination}?"
]

In [44]:
from typing import List, Dict, Tuple
import re

def generate_qa_pairs(destination: str, chain, queries: List[str]) -> List[Tuple[str, str]]:
    qa_pairs = []
    
    for query in queries:
        
        # Get relevant documents from the retriever
        result = chain.invoke({"input": query})
        
        if not result:
            print(f"Unable to get result for query {query}, skipping")
            continue
        
        retrieved_docs = result['context']
        
        # Generate answer using a template
        answer = result['answer'].answer
        citations = format_citations_to_json(result['answer'].citations, retrieved_docs)
        
        
        
        answer = f"Based on recent Reddit discussions:\n{answer}\nCitations:\n{citations}"
            
        qa_pairs.append((query, answer, citations, retrieved_docs)) # also store retireved docs for benchmarking
    
    return qa_pairs

### Generate Answer

In [45]:
qa_pairs = generate_qa_pairs(destination=destination, chain=chain, queries=rag_queries)
reddit_insights = "\n\n".join([
        f"{i+1}.\nQ: {q}\nA: {a}" for i, (q, a, citations, retrieve_docs) in enumerate(qa_pairs)
    ])

In [46]:
print(reddit_insights)

1.
Q: What are the most underrated or secret spots in Chiang Mai that tourists usually miss?
A: Based on recent Reddit discussions:
Some of the more underrated or secret spots in Chiang Mai that tourists usually miss include:

1. **Wiang Kum Kam**: A historical settlement just across the river, consisting of temple ruins rediscovered in the mid-eighties. It's often quiet with few tourists.

2. **Wat Umong**: A temple outside of town featuring tunnels, offering a different experience from the famous temples in the city center.

3. **Baan Kang Wat**: An artistic village with independent shops and cafes, offering a unique local experience.

4. **Huay Tung Thao Reservoir**: A beautiful lake where you can rent huts and have a barbecue, frequented more by locals than tourists.

5. **Mae Kampong and Mon Jam**: These areas are great for camping or glamping, offering a quiet escape from the city noise.

6. **Chiang Dao**: About 1.5 hours from Chiang Mai, featuring impressive temples like Wat Th

In [47]:
rag_system_prompt = f"""You are a knowledgeable travel assistant. Provide a comprehensive and well-structured guide for the specified destination. Your response should be detailed, accurate, and formatted using markdown.

The following information in the form of question-answer pairs with citations has been verified from recent Reddit discussions and should be incorporated into your response. Each piece of information you use must be cited with a number in brackets (e.g., [1], [2]). Only include information that has citations:

{reddit_insights}

Make sure you follow these guidelines:

1. Begin with a brief introduction about the destination.
2. Use level 2 headers (##) to separate main sections.
3. Use bolding (**) for subsections or important points within sections.
4. Include exclusively the following sections in exactly this order:
   - Best Time to Visit
   - Top Attractions
   - Local Culture and Etiquette
   - Getting Around
   - Food and Dining
   - Accommodation
   - Safety and Health
   - Budget Tips
   - Unique Experiences
   - Essential Phrases (if applicable)

5. Provide practical, up-to-date information and insider tips.
6. Use bullet points sparingly, preferring well-structured paragraphs.
7. Cite every factual claim using numbers in brackets (e.g., "The temple is beautiful[1]").
8. At the end of your response, include a "Citations" section with all referenced quotes in this exact format:
   [1] "exact quote from source" - source_url
   [2] "exact quote from source" - source_url

9. Every citation must include both the exact quote and its source URL.
10. Do not include any information from answers that express uncertainty or lack of knowledge.
11. Make sure every citation in your text corresponds to a quote in the Citations section.

Aim for a comprehensive guide that's easy to read and informative for travelers."""

In [ ]:
# print(rag_system_prompt)

### Add Citations to Answer

In [48]:
destination = "Chiang Mai"
stream = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "system", "content": rag_system_prompt},
        {"role": "user", "content": f"Provide key travel tips for {destination}"}
    ],
    stream=True
)

full_response = ""
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        content = chunk.choices[0].delta.content
        full_response += content
        
        # Clear the current output and display the updated markdown
        clear_output(wait=True)
        display(Markdown(full_response))
        
        # Add a small delay to make the streaming visible
        time.sleep(0.01)

# Chiang Mai Travel Guide

Welcome to Chiang Mai, a city nestled in the mountains of Northern Thailand known for its rich culture, historic temples, vibrant markets, and beautiful natural surroundings. Whether you're an adventure seeker, a history buff, or a culinary enthusiast, Chiang Mai offers a unique experience for every traveler.

## Best Time to Visit

The best time to visit Chiang Mai is during the cooler months of November and December. This period marks the peak season when the city is bustling with events and activities amid pleasant weather conditions. It's also outside the burning season, which typically results in poor air quality, particularly from late January through mid-April[11].

## Top Attractions

Explore Chiang Mai beyond the typical tourist paths with some of its underrated yet fascinating attractions:

- **Wiang Kum Kam**: Discover this historical settlement offering serene temple ruins, often quiet with few tourists[1].
  
- **Wat Umong**: Experience the unique underground tunnels of this temple located outside the town[1].
  
- **Baan Kang Wat**: Immerse yourself in the charm of this artistic village featuring independent shops and cafes[1].
  
- **Huay Tung Thao Reservoir**: Enjoy a relaxing day by this beautiful lake, where you can rent huts and barbecue in a tranquil environment[1].
  
- **Chiang Dao**: Venture about 1.5 hours from Chiang Mai to explore impressive temples like Wat Tham Pha Plong and Wat Tham Chiang Dao, nestled inside a cave[1].

## Local Culture and Etiquette

While specific cultural faux pas aren't detailed, it is generally advisable to dress modestly, especially when visiting temples, and to respect local customs. Avoid elephant and "hill tribe camps," as they may be unethical[14].

## Getting Around

Chiang Mai offers various transportation options. Using ride-sharing apps like Grab, Bold, Indriver, or Maxim for taxis and bikes is recommended as they are more cost-effective than tuk-tuks, which are mainly for tourists and often overpriced[6][15]. Walking is another excellent way to explore the city, particularly around the moat and old city areas[6].

## Food and Dining

Chiang Mai's culinary scene is renowned for its Northern Thai flavors. Don't miss out on:

- **Khao Soi**: A curry noodle soup, best tried at places like Kao Soy Nimman[7].
  
- **Gaeng Hung Lay**: A savory Northern Thai curry[7].
  
- **Street Food**: Explore night markets such as the Chiang Mai Gate Market and the Chang Phuak Gate Night Market for authentic local tastes[7].

## Accommodation

While specific neighborhoods for various budgets aren't detailed, staying near the moat is advantageous due to its central location and range of options[5]. Chiang Mai is generally safe, with most neighborhoods suitable for tourists, including solo female travelers[13].

## Safety and Health

Chiang Mai is considered very safe for travelers, even those traveling solo or as females, making it a favored destination among digital nomads and tourists alike[13]. However, avoid going out during afternoon storms and take care during the burning season due to air quality concerns[12][14].

## Budget Tips

Transportation via apps like Grab is economical, and local street food is both delicious and budget-friendly, with meals costing as little as 50 baht[15][10]. Renting a scooter for under $100 per week can offer more freedom if you're comfortable with driving[10].

## Unique Experiences

Dive into Chiang Mai's unique experiences such as glamping at Mae Kampong and Mon Jam or exploring the artistic enclave of Baan Kang Wat for something off the beaten path[1].

## Essential Phrases

While not detailed, learning some basic Thai phrases such as "Sawadee" for hello and "Khop Khun" for thank you can enhance your interactions with locals.

## Citations

[1] "I went to Wiang Kum Kam, it's a historical settlement just across the river. It is a series of temple ruins (not sure if you are trying to avoid temples all together) but I saw no tourists there in my visit last month." - [source_url](https://www.reddit.com/r/ThailandTourism/comments/123syod/interesting_different_things_to_do_in_chiang_mai/)

[6] "1) Don't use Tuktuks for transportation, use Grab, Bold, Indriver or Maxim. If you want to just try a Tuktuk for fun go for it, but it's mostly a tourist thing and prices are much higher that other transport." - [source_url](https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/)

[7] "Hung Lay curry." - [source_url](https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/)

[10] "100 Thai Baht is about $3 USD - Back in January 2024, 100 Thai Baht was just under $3 USD." - [source_url](https://www.reddit.com/r/chiangmai/comments/1dholk5/my_time_in_chiang_mai_jan_2024_would_love_to_hear/)

[11] "Now is extremely low season so there is nobody here. Come back peak season November December and it's a whole other story. People and events/workshops everywhere!" - [source_url](https://www.reddit.com/r/ThailandTourism/comments/14dajv5/chiang_mai_was_not_for_me/)

[13] "Yes. Chiang Mai is safe for solo female travelers." - [source_url](https://www.reddit.com/r/chiangmai/comments/17x9b7r/chiang_mai_is_a_good_place_in_thailand/)

[14] "Avoid nothing (except elephant camps and those crazy “hill tribe camps”)." - [source_url](https://www.reddit.com/r/chiangmai/comments/1evxoyu/4_days_trip_in_chiang_mai_any_suggestions_for/)

[15] "Yes Chiang Mai is a great city. In the end of February there can be some smoke but it varies every year. Grab, Bolt, Indriver, Maxim are the best apps for taxi and bike. Tuk tuks are expensive and often try to rip you off. It's a very safe place." - [source_url](https://www.reddit.com/r/chiangmai/comments/17x9b7r/chiang_mai_is_a_good_place_in_thailand/)

### Evaluate citations using NLI model (from RAG - tutorial slides)

In [ ]:
# download huggingface model and do stuff

### Present With Rag / Without RAG relevance (the evaluation step)

In [50]:
pip install bert-score

Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 192, in version
    return parse_version(self._dist.version)
  File "c:\Users\Daniel\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "c:\Users\Daniel\anaconda3\lib\site-p

In [ ]:
from bert_score import score, BERTScorer
def evaluate_response_citations_similarity(
    llm_response: str,
    citations: List[str],
    model_type: str = "roberta-large",
    language: str = "en",
    batch_size: int = 32
):
    # Repeat the LLM response for each citation
    scorer = BERTScorer(model_type='bert-base-uncased')
    precision = np.array([])
    recall = np.array([])
    f1 = np.array([])
    for citation in citations:
        print(citation)
        P, R, F1 = scorer.score([llm_response], [citation])
        precision = np.append(precision, P)
        recall = np.append(recall, R)
        f1 = np.append(f1, F1)
    
    # Calculate average scores
    avg_precision = np.mean(precision)
    avg_recall = np.mean(recall)
    avg_f1 = np.mean(f1)
    
    # Prepare results
    results = {
        'avg_precision': avg_precision,
        'avg_recall': avg_recall,
        'avg_f1': avg_f1,
        'individual_scores': list(zip(precision, recall, f1))
    }
    
    return results


In [93]:
citation_list = []
for query, answer, citations, retrieved_docs in qa_pairs:
    json_obj = json.loads(citations)
    for citation in json_obj:
        citation_list.append(citation["quote"])

print(len(citation_list))
for citation in citation_list:
    if citation == "":
        citation_list.remove(citation)
print(len(citation_list))

48
48


In [90]:
citation_list = []
for query, answer, citations, retrieved_docs in qa_pairs:
    json_obj = json.loads(citations)
    for citation in json_obj:
        citation_list.append(citation["quote"])

results = evaluate_response_citations_similarity(full_response, citations)

print(f"Average Precision: {results['avg_precision']:.4f}")
print(f"Average Recall: {results['avg_recall']:.4f}")
print(f"Average F1: {results['avg_f1']:.4f}")

print("\nIndividual Scores:")
for i, (p, r, f) in enumerate(results['individual_scores']):
    print(f"Citation {i+1}: Precision = {p:.4f}, Recall = {r:.4f}, F1 = {f:.4f}")

tensor([0.1570]) tensor([0.3938]) tensor([0.2245])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1588]) tensor([0.2762]) tensor([0.2017])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1428]) tensor([0.2453]) tensor([0.1805])
tensor([0.1566]) tensor([0.2843]) tensor([0.2019])
tensor([0.1591]) tensor([0.3089]) tensor([0.2100])
tensor([0.1548]) tensor([0.2790]) tensor([0.1991])
tensor([0.1304]) tensor([0.2921]) tensor([0.1803])
tensor([0.1479]) tensor([0.2937]) tensor([0.1968])
tensor([0.1516]) tensor([0.3007]) tensor([0.2016])
tensor([0.1951]) tensor([0.3813]) tensor([0.2581])
tensor([0.1391]) tensor([0.2388]) tensor([0.1758])
tensor([0.1437]) tensor([0.3159]) tensor([0.1976])
tensor([0.1428]) tensor([0.2453]) tensor([0.1805])
tensor([0.1804]) tensor([0.4231]) tensor([0.2530])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1413]) tensor([0.3327]) tensor([0.1984])
tensor([0.1676]) tensor([0.2799]) tensor([0.2097])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1428]) tensor([0.2453]) tensor([0.1805])
tensor([0.1315]) tensor([0.2426]) tensor([0.1706])
tensor([0.1548]) tensor([0.2790]) tensor([0.1991])
tensor([0.1591]) tensor([0.3089]) tensor([0.2100])
tensor([0.1632]) tensor([0.3438]) tensor([0.2213])
tensor([0.1516]) tensor([0.3007]) tensor([0.2016])
tensor([0.1428]) tensor([0.2453]) tensor([0.1805])
tensor([0.1804]) tensor([0.4231]) tensor([0.2530])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1428]) tensor([0.2453]) tensor([0.1805])
tensor([0.1672]) tensor([0.3415]) tensor([0.2245])
tensor([0.1516]) tensor([0.3007]) tensor([0.2016])
tensor([0.1566]) tensor([0.2843]) tensor([0.2019])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1479]) tensor([0.2937]) tensor([0.1968])
tensor([0.1366]) tensor([0.2805]) tensor([0.1837])
tensor([0.1391]) tensor([0.2388]) tensor([0.1758])
tensor([0.1471]) tensor([0.2905]) tensor([0.1953])
tensor([0.1310]) tensor([0.2059]) tensor([0.1601])
tensor([0.1413]) tensor([0.2860]) tensor([0.1892])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1363]) tensor([0.2874]) tensor([0.1849])
tensor([0.1471]) tensor([0.2905]) tensor([0.1953])
tensor([0.1391]) tensor([0.2388]) tensor([0.1758])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1391]) tensor([0.2388]) tensor([0.1758])
tensor([0.1566]) tensor([0.2843]) tensor([0.2019])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1471]) tensor([0.2905]) tensor([0.1953])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1413]) tensor([0.2860]) tensor([0.1892])
tensor([0.1304]) tensor([0.2921]) tensor([0.1803])
tensor([0.1516]) tensor([0.3007]) tensor([0.2016])
tensor([0.1471]) tensor([0.2905]) tensor([0.1953])
tensor([0.1632]) tensor([0.3438]) tensor([0.2213])


tensor([0.]) tensor([0.]) tensor([0.])
tensor([0.1479]) tensor([0.2937]) tensor([0.1968])
tensor([0.1391]) tensor([0.2388]) tensor([0.1758])


KeyboardInterrupt: 